run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
